BusTicketBookingSystem/BusTicketBookingSystem/Controllers/ReservationController.cs
using BusTicketBookingSystem.Filters;
using BusTicketBookingSystem.Models;
using BusTicketBookingSystem.Models.Ticket;
using BusTicketBookingSystem.Models.Vehicle;
using BusTicketBookingSystem.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace BusTicketBookingSystem.Controllers
{
    public class ReservationController : Controller
    {
        private OperationDataContext context = null;

        public ReservationController()
        {
            context = new OperationDataContext();
        }

        // GET: Reservation

        public ActionResult Index()
        {
            // create the placeList variable
            List<ReservationModel> reservationList = new List<ReservationModel>();

            // perform linq operation
            var query = from reservation in context.Reservations select reservation;

            // store the query to list
            var reservations = query.ToList();

            // looping through all items in roles
            foreach (var reservationItem in reservations)
            {
                reservationList.Add(new ReservationModel()
                {
                    Id = reservationItem.Id,
                    TotalSeat = reservationItem.TotalSeat,
                    SeatNumber = reservationItem.SeatNumber,
                    PurchasedOn = reservationItem.PurchasedOn,
                    PassengerID = reservationItem.PassengerID,
                    BusID = reservationItem.BusID,
                    TotalAmount = reservationItem.TotalAmount,
                    IsConfirmed = reservationItem.IsConfirmed
                });
            }

            return View(reservationList);
        }

        // GET: Reservation/Details/5
        public ActionResult Details(int id)
        {
            var query = from reservation in context.Reservations
                        join bus in context.BusVehicles
                        on reservation.BusID equals bus.Id
                        join passenger in context.Passengers
                        on reservation.PassengerID equals passenger.Id
                        where reservation.Id == id
                        select new ReservationModel
                        {
                            Id = reservation.Id,
                            TotalSeat = reservation.TotalSeat,
                            PurchasedOn = reservation.PurchasedOn,
                            PassengerID = reservation.PassengerID,
                            PassengerName = $"{passenger.FirstName} {passenger.LastName}",
                            PhoneNumber = passenger.PhoneNumber,
                            BankName = passenger.BankName,
                            BankAccount = passenger.BankAccountNumber,
                            BusOrigin = bus.Route.Origin,
                            BusDestination = bus.Route.Destination,
                            BusName = bus.Name,
                            BusClass = bus.Class,
                            BusCapacity = bus.Capacity,
                            DepartureTime = bus.DepartureTime.ToString(),
                            TotalAmount = reservation.TotalAmount,
                            IsConfirmed = reservation.IsConfirmed,
                            PaymentProof = reservation.PaymentProof
                        };

            return View(query.SingleOrDefault());
        }

        // GET: Reservation/Create
        [HttpGet]
        [InitializeSearchBusForm]
        [AllowAnonymous]
        public ActionResult Create()
        {
            ReservationModel model = new ReservationModel();

            return View(model);
        }

        // GET: Reservation/Search
        [HttpGet]
        [InitializeSearchBusForm]
        [AllowAnonymous]
        public ActionResult Search(SearchBusViewModel busTicket)
        {
            ViewBag.Errors = new List<string>();

            if (ModelState.IsValid)
            {
                DateTime departureTime = DateTime.Parse(busTicket.DepartureTime)
                                                 .AddHours(busTicket.DepartureTimeHour);

                if (departureTime < DateTime.Now)
                {
                    ModelState.AddModelError("AlreadyDeparted", "The time of departure for your search has already passed.");
                    return View(nameof(this.Index), busTicket);
                }

                var busRoute = context.Routes
                                      .Where(r => r.Origin == busTicket.Departure)
                                      .Where(r => r.Destination == busTicket.Arrival)
                                      .SingleOrDefault();

                if (busRoute == null)
                {
                    ModelState.AddModelError("InvalidRoute", "Departure and arrival cities should be different.");
                    return View(nameof(this.Index), busTicket);
                }

                var bus = context.BusVehicles
                                 .Where(b => b.DepartureTime >= departureTime)
                                 .Where(b => b.RouteID == busRoute.Id)
                                 .OrderBy(b => b.DepartureTime)
                                 .Take(3)
                                 .Select(bv => new AvailableBusViewModel()
                                 {
                                     Id = bv.Id,
                                     Capacity = bv.Capacity,
                                     Class = bv.Class,
                                     Route = bv.Route,
                                     Fare = bv.Fare,
                                     DepartureTime = bv.DepartureTime,
                                     //PassengersCount = context.Reservations
                                     //                         .Where(r => r.BusID == bv.Id)
                                     //                         .Where(r => r.IsConfirmed == true)
                                     //                         .Select(r => r.TotalSeat)
                                     //                         .DefaultIfEmpty()
                                     //                         .Sum()
                                 })
                                .ToList();

                return View(bus);
            }

            return View();
        }

        // GET /ticket/purchase/{id}
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Purchase(int id)
        {
            var bus = context.BusVehicles
                             .Where(b=>b.Id==id)
                             .SingleOrDefault();

            var viewModel = new AvailableBusViewModel()
            {
                Id = bus.Id,
                Capacity = bus.Capacity,
                Class = bus.Class,
                Route = bus.Route,
                Fare = bus.Fare,
                DepartureTime = bus.DepartureTime,
            };

            return View(viewModel);
        }

        // POST /ticket/purchase
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Purchase(PurchaseTicketViewModel ticket)
        {
            try
            {
                // TODO: Add insert logic here
                var currentUserId = User.Identity.GetUserId();
                var bus = context.BusVehicles
                                 .Where(b => b.Id == ticket.Id)
                                 .SingleOrDefault();

                if (bus == null)
                {
                    return new HttpStatusCodeResult(404);
                }

                var viewModel = new AvailableBusViewModel()
                {
                    Id = bus.Id,
                    Capacity = bus.Capacity,
                    Class = bus.Class,
                    Route = bus.Route,
                    Fare = bus.Fare,
                    DepartureTime = bus.DepartureTime,
                };

                if (bus.DepartureTime < DateTime.Now)
                {
                    ViewBag.Error = "This bus has already departed.";
                    return View(viewModel);
                }
                else if (bus.DepartureTime > DateTime.Now.AddDays(AppConstants.MAX_DAYS_BEFORE_RESERVATION))
                {
                    ViewBag.Error = "You can only purchase tickets as late as two weeks before departure.";
                    return View(viewModel);
                }

                Reservation reservation = new Reservation()
                {
                    TotalSeat = ticket.PassengersCount,
                    PurchasedOn = DateTime.Now,
                    PassengerID = context.Passengers
                                         .Where(u => u.UserID == currentUserId)
                                         .Select(p => p.Id)
                                         .SingleOrDefault(),
                    BusID = bus.Id,
                    TotalAmount = ticket.PassengersCount * bus.Fare,
                    IsConfirmed = false
                };

                context.Reservations.InsertOnSubmit(reservation);
                context.SubmitChanges();

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }            
        }

        // GET /tickets
        [HttpGet]
        [Authorize]
        public ActionResult List()
        {
            string currentUserId = User.Identity.GetUserId();

            var query = from reservation in context.Reservations
                        join bus in context.BusVehicles
                        on reservation.BusID equals bus.Id
                        join passenger in context.Passengers
                        on reservation.PassengerID equals passenger.Id

BusTicketBookingSystem/BusTicketBookingSystem/Controllers/RolesController.cs
using BusTicketBookingSystem.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BusTicketBookingSystem.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            // Populate Dropdown Lists
            var context = new Models.ApplicationDbContext();

            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
                           new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;

            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
                           new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            ViewBag.Message = "";

            return View();
        }

        // GET: /Roles/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {

            try
            {
                var context = new Models.ApplicationDbContext();
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.Message = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string RoleName)
        {
            var context = new Models.ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string roleName)
        {
            var context = new Models.ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                var context = new Models.ApplicationDbContext();
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //  Adding Roles to a user
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {
            var context = new Models.ApplicationDbContext();

            if (context == null)
            {
                throw new ArgumentNullException("context", "Context must not be null.");
            }

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(user.Id, RoleName);


            ViewBag.Message = "Role created successfully !";

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            return View("Index");
        }


        //Getting a List of Roles for a User
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                var context = new Models.ApplicationDbContext();
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                var userStore = new UserStore<ApplicationUser>(context);
                var userManager = new UserManager<ApplicationUser>(userStore);
                ViewBag.RolesForThisUser = userManager.GetRoles(user.Id);


                // Repopulate Dropdown Lists
                var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = rolelist;
                var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
                new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
                ViewBag.Users = userlist;
                ViewBag.Message = "Roles retrieved successfully !";
            }

            return View("Index");
        }

        //Deleting a User from A Role
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var account = new AccountController();
            var context = new Models.ApplicationDbContext();
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);


            if (userManager.IsInRole(user.Id, RoleName))
            {
                userManager.RemoveFromRole(user.Id, RoleName);
                ViewBag.Message = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.Message = "This user doesn't belong to selected role.";
            }

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            return View("Index");
        }

    }
}

BusTicketBookingSystem/BusTicketBookingSystem/Views/Shared/_Carousel.cshtml
@{
    Layout = null;
}

<div id="carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel" data-slide-to="0" class=""></li>
        <li data-target="#carousel" data-slide-to="1" class="active"></li>
        <li data-target="#carousel" data-slide-to="2" class=""></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item">
            <img class="first-slide " src="~/Content/Images/carrousel1.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <blockquote class="blockquote-reverse">
                        <p>Travel is the only thing you buy that makes you richer.</p>
                        <small class="text-primary">Anonymous</small>
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="item active">
            <img class="second-slide " src="~/Content/Images/carrousel2.jpg" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <blockquote class="blockquote-reverse">
                        <p>The world is a book, and those who do not travel read only one page.</p>
                        <small class="text-primary">Saint Augustine</small>
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="item">
            <img class="third-slide " src="~/Content/Images/carrousel3.jpg" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <blockquote class="blockquote-reverse">
                        <p>A journey is best measured in friends, rather than miles.</p>
                        <small class="text-primary">Tim Cahill</small>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

BusTicketBookingSystem/BusTicketBookingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bus Ticket Booking System</title>
    <link href="~/Content/AdvancePasswordValidation.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar-wrapper">
        @Html.Partial("_NavigationBar")
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <div class="container">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bus Ticket Booking System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/vendor")
    <script src="~/Scripts/AdvancePasswordValidation.js"></script>
    
    @RenderSection("scripts", required: false)
</body>
</html>

BusTicketBookingSystem/BusTicketBookingSystem/Views/Shared/_NavigationBar.cshtml
@{ 
    Layout = null;
}

<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("directions_bus", "Index", "Home", new { area = "" }, new { @class = "navbar-brand material-icons" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (User.IsInRole("Admin"))
                {
                    <li>@Html.ActionLink("Search bus", "Create", "Reservation")</li>
                    <li>@Html.ActionLink("Purchased ticket", "Index", "Reservation")</li>
                    <li>@Html.ActionLink("Role Manager", "Index", "Roles")</li>
                    <li>@Html.ActionLink("Manage City", "Index", "Place")</li>
                    <li>@Html.ActionLink("Manage Route", "Index", "Route")</li>
                    <li>@Html.ActionLink("Manage Bus", "Index", "BusVehicle")</li>
                }
                else
                {
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Search bus", "Create", "Reservation")</li>
                    if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Purchased ticket", "List", "Reservation")</li>
                    }
                }      
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>